#!/usr/bin/env sh

touchpad="etps/2-elantech-touchpad"

brightness=$(< "$HOME/.cache/backlight")
brightnessctl set $brightness

hyprctl dispatch -- exec swww init --format xrgb &

autostart="gentoo-pipewire-launcher swaync hypridle ydotoold mpd mpdscribble set-background notify-send-log battery-warn" # mpc-auto-play"
for program in $autostart; do
	hyprctl dispatch exec "$program" &
done

hyprctl dispatch -- exec solaar -w=hide &

# make it just toggle off by default instead of disabling it
hyprctl keyword "device:${touchpad}:enabled" false

# start programs
hyprctl dispatch -- exec librewolf &
hyprctl dispatch -- exec flatpak run dev.vencord.Vesktop &

tmux new-session -d -s "home" &
tmux new-session -d -s "code" &

tmux new-window -tcode: -c "$HOME/Documents/code" &
tmux new-window -thome: -c "$HOME/Music" ncmpcpp &
tmux new-window -thome: -c "$HOME" neomutt &

hyprctl dispatch -- exec "[workspace 3 silent]" "$TERMINAL -e tmux attach -thome" &
