[[manager.append_keymap]]
on   = [ "<C-c>", 'w' ]
run  = "plugin set-wallpaper"
desc = "Set selected file as wallpaper"

[[manager.append_keymap]]
on   = [ "<C-c>", 'd' ]
run  = "plugin ripdrag"
desc = "Insert selected files into ripdrag"

[[manager.append_keymap]]
on   = [ "<C-k>" ]
run  = "seek -5"
desc = "Seek up 5 units in the preview"

[[manager.append_keymap]]
on   = [ "<C-j>" ]
run  = "seek 5"
desc = "Seek down 5 units in the preview"
