[font]
size = 9.0

[font.bold]
family = "monospace"
style = "Bold"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
style = "Regular"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Alt"
[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Alt|Shift"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Alt|Shift"

[scrolling]
history = 10000
multiplier = 5

[terminal.shell]
program = "/bin/zsh"

[window]
dynamic_padding = false

[general]
import = [
    #"~/.config/alacritty/themes/{theme}.toml"
    "~/.config/alacritty/themes/snow-dark.toml"
]
